name: Check available lxc images
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  setupv1:
    name: Setup CGroupV1
    runs-on: ubuntu-20.04
    continue-on-error: true
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: check old image server
        run: lxc remote list
      - name: setup incus
        run: ./setup.sh focal
      - name: Available incus alias
        run: ./alias.sh
      - name: Available incus images
        run: ./images.sh
      - name: Available incus ubuntu images
        run: ./ubuntu.sh
  setupv2:
    name: Setup CGroupV2
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: check old image server
        run: lxc remote list
      - name: setup incus
        run: ./setup.sh jammy
      - name: Available incus alias
        run: ./alias.sh
      - name: Available incus images
        run: ./images.sh
      - name: Available incus ubuntu images
        run: ./ubuntu.sh
  launchv1:
    name: Launch CGroupV1
    runs-on: ubuntu-20.04
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        label:
          - CentOS 7
          - AmazonLinux 2
          - AmazonLinux 2023
        include:
          - label: CentOS 7
            image: images:centos/7
          - label: AmazonLinux 2
            image: images:amazonlinux/2
          - label: AmazonLinux 2023
            image: images:amazonlinux/2023
    steps:
      - uses: actions/checkout@v4
      - name: setup incus
        run: ./setup.sh focal
      - name: ${{ matrix.label }}
        run: ./launch.sh ${{ matrix.image }}
